[build]
  command = "yarn build"
  publish = "build"

[[redirects]]
  from = "/fonts.css"
  to = "https://fonts.googleapis.com/css2?family=Catamaran:wght@400;600;700&family=Source+Serif+Pro:ital@0;1&display=swap"
  status = 200
[[redirects]]
  from = "/stats/firebase-performance.js"
  to = "https://www.gstatic.com/firebasejs/8.3.3/firebase-performance-standalone.js"
  status = 200
[[redirects]]
  from = "/stats/plausible.js"
  to = "https://p.ivoberger.com/js/index.js"
  status = 200
