[build]
  command = "yarn build"
  publish = "build"

[[redirects]]
  from = "/css/fonts.css"
  to = "https://fonts.googleapis.com/css2?family=Catamaran&family=Source+Serif+Pro:wght@400;600;700&display=swap"
  status = 200
[[redirects]]
  from = "/scripts/firebase-performance.js"
  to = "https://www.gstatic.com/firebasejs/8.3.3/firebase-performance-standalone.js"
  status = 200
[[redirects]]
  from = "/scripts/stats.js"
  to = "https://p.ivoberger.com/js/index.js"
  status = 200
