[build]
  command = "yarn build"
  publish = "build"

[[redirects]]
  from = "/css/fonts.css"
  to = "https://fonts.googleapis.com/css2?family=Catamaran&family=Source+Serif+Pro:wght@400;600;700&display=swap"
  status = 200
